// Eclipse Competition — content source of truth
window.EC_DATA = {
  brand: {
    founded: "November 2023",
    platform: "iRacing",
    ig: "@eclipse_competition",
    discord: "https://discord.gg/CBtQMmcksE",
  },
  stats: [
    { n: "10+", l: "Endurance Race Wins" },
    { n: "2",   l: "Sebring 12 Hour Wins" },
    { n: "1",   l: "Indy 500 Win" },
    { n: "3",   l: "Formula League Championships" },
    { n: "5K+", l: "Average Team iRating" },
    { n: "2023",l: "Founded" },
  ],
  trophies: [
    { year: "2025", title: "Daytona 24 Winner",        class: "GTP",                drivers: "Moss · Sherlock · Fairbairn · Smartt", img: "assets/win-daytona-24.png",          tag: "SPECIAL EVENT" },
    { year: "2025", title: "Sebring 12 Hour · P1",     class: "GTP",                drivers: "Costello · Sherlock · DeFabis",       img: "assets/trophy-sunset-p1.jpg",        tag: "RACE WIN" },
    { year: "2025", title: "Indy 500 Winner",          class: "Dallara IR-18",      drivers: "Tristan Moss",                        img: "assets/win-indy500-2025.png",        tag: "GRAND SLAM" },
    { year: "2025", title: "Global Endurance · P1",    class: "GTP",                drivers: "Sherlock · DeFabis",                  img: "assets/trophy-hockenheim-alt.jpg",   tag: "RACE WIN" },
    { year: "2025", title: "Petit Le Mans Winner",     class: "GTP",                drivers: "Sherlock · Costello · Fairbairn",     img: "assets/win-grand-slam.jpg",          tag: "SPECIAL EVENT" },
    { year: "2025", title: "FIS Team Champions",       class: "Formula Indy Series",drivers: "Sherlock · DeFabis · Costello",       img: "assets/win-double-podium.png",       tag: "CHAMPIONSHIP" },
    { year: "2025", title: "FSS Teams Champions",      class: "Formula Sim Series", drivers: "8 combined wins",                     img: "assets/win-fss-champions.jpg",       tag: "CHAMPIONSHIP" },
    { year: "2025", title: "FSS Drivers' Champion",    class: "Formula Sim Series", drivers: "Titus Sherlock",                      img: "assets/trophy-fss-drivers-champ.jpg",tag: "CHAMPIONSHIP" },
  ],
  owners: [
    {
      name: "Michael Costello",
      role: "Founder · Team Principal",
      initials: "MC",
      img: "assets/face-michael-costello.png",
      bio: "Founder and day-to-day principal of Eclipse. Leads car setup development, roster strategy, and the shift toward IMSA and Global Endurance programs. Drives across GTP, LMP2 and Formula.",
      tint: "purple",
    },
    {
      name: "Titus Sherlock",
      role: "Co-Founder · Sporting Director",
      initials: "TS",
      img: "assets/face-titus-sherlock.webp",
      bio: "Co-founded Eclipse alongside Michael in November 2023. Owns sporting regulations, rostering, and driver conduct. Petit Le Mans winner, FSS Drivers' Champion, and FIS race winner behind the wheel.",
      tint: "cyan",
    },
    {
      name: "Sam McDougall",
      role: "Co-Owner · Livery & Radical Program",
      initials: "SM",
      img: "assets/face-sam-mcdougall.jpg",
      bio: "Co-owner, Radical program wheelman, and the hand behind Eclipse's livery family — from the purple LMDh to the FIS fleet.",
      tint: "purple",
    },
  ],
  staff: [
    {
      name: "Tanner DeFabis",
      role: "Admin · Formula Program",
      initials: "TD",
      img: "assets/face-tanner-defabis.png",
      bio: "Admin and open-wheel lead. Podium finisher in Formula Indy Series, part of the Indy 500 lineup.",
    },
    {
      name: "Jeremy Fairbairn",
      role: "Admin · Endurance Lead",
      initials: "JF",
      img: "assets/face-jeremy-fairbairn.png",
      bio: "Admin and endurance specialist. Petit Le Mans co-winner, anchoring the long-run program across Daytona 24, Sebring 12, Bathurst and Spa.",
    },
    {
      name: "Griffin Yellin",
      role: "Setup Engineer",
      initials: "GY",
      img: "assets/face-griffin-yellin.jpeg",
      bio: "Vehicle dynamics lead. Co-building Eclipse's upcoming AI-assisted setup platform with Michael and Tristan.",
    },
    {
      name: "Tristan Moss",
      role: "Admin · Setup Advisor",
      initials: "TM",
      img: "assets/face-tristan-moss.jpg",
      bio: "Indy 500 winner and Eclipse setup advisor. Works alongside Michael on setup development, strategy and operations, and helps keep the programs moving day to day.",
    },
    {
      name: "Sybren Stoel",
      role: "Partner · Owner, SJS Games",
      initials: "SS",
      bio: "Strategic partner. Owner of SJS Games and long-time collaborator on Eclipse programs and events.",
    },
  ],
  drivers: [
    { name: "Max Taylor",          note: "IndyNXT Race Winner",   initials: "MT", img: "assets/face-max-taylor.jpg",            programs: ["Formula", "GTP"] },
    { name: "Devlin DeFrancesco",  note: "IndyCar · Endurance",    initials: "DD", img: "assets/face-devlin-defrancesco.webp",   programs: ["Formula", "GTP"] },
    { name: "Peter Dempsey",       note: "Indy Lights Winner",     initials: "PD", img: "assets/face-peter-dempsey.jpeg",        programs: ["GTP", "LMP2"] },
    { name: "Evagoras Papasavvas", note: "Endurance · GTP",        initials: "EP", img: "assets/face-evagoras-papasavvas.webp",  programs: ["GTP", "LMP2"] },
    { name: "Barrett Wolfe",       note: "Endurance · GT3",        initials: "BW", img: "assets/face-barrett-wolfe.webp",        programs: ["GT3"] },
    { name: "Drew Szuch",          note: "Formula · Endurance",    initials: "DS", img: "assets/face-drew-szuch.jpeg",           programs: ["Formula", "LMP2"] },
    { name: "Alex Berg",           note: "British F4 Champion",    initials: "AB", img: "assets/face-alex-berg.jpg",             programs: ["GTP", "LMP2"] },
    { name: "Bryson Morris",       note: "Young Gun · Formula",    initials: "BM", img: "assets/face-bryson-morris.png",         programs: ["Formula"] },
  ],
  events: [
    { mo: "JAN", d: "9–10",  t: "Roar Before the 24",     v: "Daytona International Speedway",  c: "LMP2" },
    { mo: "JAN", d: "16–18", t: "Daytona 24",              v: "Daytona International Speedway",  c: "GTP · LMP2 · GT3", featured: true },
    { mo: "FEB", d: "20–22", t: "Bathurst 12",             v: "Mount Panorama Circuit",          c: "GT3", featured: true },
    { mo: "MAR", d: "27–29", t: "Sebring 12",              v: "Sebring International Raceway",   c: "GTP · LMP2 · GT3", featured: true },
    { mo: "MAY", d: "1–3",   t: "Nürburgring 24h",         v: "Nürburgring-Gesamtstrecke 24h",   c: "GT3" },
    { mo: "MAY", d: "5–11",  t: "Indy 500 · Fixed",        v: "Indianapolis Motor Speedway",     c: "IndyCar" },
    { mo: "MAY", d: "12–18", t: "Indy 500 · Open",         v: "Indianapolis Motor Speedway",     c: "IndyCar", featured: true },
    { mo: "JUN", d: "19–21", t: "Watkins Glen 6 Hour",     v: "Watkins Glen International",      c: "GTP · LMP2 · GT3" },
    { mo: "JUL", d: "10–12", t: "Spa 24",                  v: "Circuit de Spa-Francorchamps",    c: "GT3" },
    { mo: "JUL", d: "24–26", t: "6 Hours of Road America", v: "Road America",                    c: "GTP · LMP2 · GT3" },
    { mo: "SEP", d: "10–15", t: "Suzuka 1000km",           v: "Suzuka Circuit",                  c: "GT3" },
    { mo: "SEP", d: "18–20", t: "Britcar 24",              v: "Silverstone",                     c: "GT3" },
    { mo: "SEP", d: "25–27", t: "Petit Le Mans",           v: "Michelin Raceway Road Atlanta",   c: "GTP · LMP2 · GT3", featured: true },
    { mo: "OCT", d: "16–18", t: "8 Hours of Indianapolis", v: "Indianapolis Motor Speedway",     c: "GT3" },
  ],
  gallery: [
    { img: "assets/media-michael-portrait.jpg", caption: "MICHAEL COSTELLO · FOUNDER",    tag: "PIT WALL" },
    { img: "assets/media-03.png",               caption: "GTP · NIGHT PACE",              tag: "RACE" },
    { img: "assets/media-02.png",               caption: "GLOBAL ENDURANCE · OCTOBER 2025", tag: "RACE" },
    { img: "assets/media-04.png",               caption: "SEBRING 12 · MARCH 2026",       tag: "RACE" },
    { img: "assets/media-01.jpg",               caption: "SEPTEMBER 2025 · ENDURANCE",    tag: "RACE" },
  ],
  sponsors: [
    { name: "Mosaic Animal Health at St. Hubert's", short: "MOSAIC AHC",     type: "PARTNER", logo: "assets/sp-st-huberts.webp" },
    { name: "Ronald McDonald House Charities",      short: "RMHC",           type: "CHARITY", logo: "assets/sp-rmhc.png" },
    { name: "Hope 4 AL",                            short: "HOPE4AL",        type: "CHARITY", logo: "assets/sp-hope4al.webp" },
    { name: "ProGuard Automotive",                  short: "PROGUARD",       type: "SPONSOR", logo: "assets/sp-proguard.jpg" },
    { name: "Destination Athlete",                  short: "DEST. ATHLETE",  type: "SPONSOR", logo: "assets/sp-destination-athlete.jpeg" },
    { name: "EDA Frames Eyewear",                   short: "EDA FRAMES",     type: "SPONSOR", logo: "assets/sp-eda-frames.jpg" },
    { name: "Rayne Nutrition",                      short: "RAYNE",          type: "SPONSOR", logo: "assets/sp-rayne.jpg" },
    { name: "iwis",                                 short: "IWIS",           type: "SPONSOR", logo: "assets/sp-iwis.webp" },
    { name: "Bell Helmets",                         short: "BELL",           type: "SPONSOR", logo: "assets/sp-bell.jpeg" },
    { name: "100%",                                 short: "100%",           type: "SPONSOR", logo: "assets/sp-ride-100.png" },
  ],
};
