// Eclipse Competition — content source of truth
window.EC_DATA = {
  brand: {
    founded: "November 2023",
    platform: "iRacing",
    ig: "@eclipse_competition",
    igUrl: "https://instagram.com/eclipse_competition",
    discord: "https://discord.gg/CBtQMmcksE",
    // TODO Griffin: drop the team's partnership inbox in here and the contact
    // section will render an email button automatically. Leave "" to hide it.
    email: "",
  },
  // Ribbon: bump `id` every time this copy changes, otherwise anyone who
  // dismissed the previous ribbon will never see the new one.
  latest: {
    id: "road-america-6h-2026",
    title: "Road America 6 Hour",
    detail: "Argyros · Moss",
  },
  stats: [
    { n: "10+", l: "Endurance Race Wins" },
    { n: "2",   l: "Sebring 12 Hour Wins" },
    { n: "1",   l: "Indy 500 Win" },
    { n: "4",   l: "Formula League Championships" },
    { n: "5K+", l: "Average Team iRating" },
    { n: "2023",l: "Founded" },
  ],
  // size: "wide" = full-width banner · "half" = two columns · omitted = 4/5 card
  // pos:  object-position override, for crops that need steering
  trophies: [
    { year: "2026", title: "Road America 6 Hour · P1", class: "LMP2",              drivers: "G3 Argyros · Tristan Moss",           img: "assets/win-road-america-6h-lmp2.webp",  tag: "LATEST RESULT", size: "wide" },
    { year: "2026", title: "Brickyard 400 Winner",     class: "NASCAR Cup",         drivers: "Tristan Moss",                        img: "assets/win-brickyard-400-moss.webp",    tag: "SPECIAL EVENT", size: "half" },
    { year: "2026", title: "Pocono Race Winner",       class: "FIS Round 2",        drivers: "Tanner DeFabis",                      img: "assets/win-fis-r2-pocono-defabis.webp", tag: "RACE WIN",      size: "half" },
    { year: "2025", title: "Majors 24 Hours of Le Mans", class: "GTP · Hypercar",   drivers: "Sherlock · Papasavvas · Costello · McDougall", img: "assets/win-lemans-majors.webp", tag: "GRAND SLAM" },
    { year: "2026", title: "FSS Champion",             class: "Formula Sim Series", drivers: "Michael Costello",                    img: "assets/win-fss-champion-costello.webp", tag: "CHAMPIONSHIP" },
    { year: "2025", title: "Daytona 24 Winner",        class: "GTP",                drivers: "Moss · Sherlock · Fairbairn · Smartt", img: "assets/win-daytona-24.webp",           tag: "SPECIAL EVENT" },
    { year: "2025", title: "Sebring 12 Hour · P1",     class: "GTP",                drivers: "Costello · Sherlock · DeFabis",       img: "assets/trophy-sunset-p1.webp",          tag: "RACE WIN" },
    { year: "2025", title: "Indy 500 Winner",          class: "Dallara IR-18",      drivers: "Tristan Moss",                        img: "assets/win-indy500-2025.webp",          tag: "GRAND SLAM" },
    { year: "2025", title: "Global Endurance · P1",    class: "GTP",                drivers: "Sherlock · DeFabis",                  img: "assets/trophy-hockenheim-alt.webp",     tag: "RACE WIN" },
    { year: "2025", title: "Petit Le Mans Winner",     class: "GTP",                drivers: "Sherlock · Costello · Fairbairn",     img: "assets/win-grand-slam.webp",            tag: "SPECIAL EVENT" },
    { year: "2025", title: "FIS Team Champions",       class: "Formula Indy Series",drivers: "Sherlock · DeFabis · Costello",       img: "assets/win-double-podium.webp",         tag: "CHAMPIONSHIP" },
    { year: "2025", title: "FSS Teams Champions",      class: "Formula Sim Series", drivers: "8 combined wins",                     img: "assets/win-fss-champions.webp",         tag: "CHAMPIONSHIP" },
    { year: "2025", title: "FSS Drivers' Champion",    class: "Formula Sim Series", drivers: "Titus Sherlock",                      img: "assets/trophy-fss-drivers-champ.webp",  tag: "CHAMPIONSHIP" },
  ],
  owners: [
    {
      name: "Michael Costello",
      role: "Founder · Team Principal",
      initials: "MC",
      img: "assets/face-michael-costello.webp",
      bio: "Founded Eclipse in November 2023 and still runs it day to day. Races USF Pro 2000 in the real world. Builds most of the car setups himself and picks who races. Won the 2026 FSS championship and drives GTP, LMP2 and Formula.",
      tint: "purple",
    },
    {
      name: "Titus Sherlock",
      role: "Co-Founder · Sporting Director",
      initials: "TS",
      img: "assets/face-titus-sherlock.webp",
      bio: "Co-founded Eclipse with Michael in November 2023. FR Americas Champion in the real world. Writes the sporting regs and handles driver conduct. Won Petit Le Mans and the FSS drivers' title from the seat.",
      tint: "cyan",
    },
    {
      name: "Sam McDougall",
      role: "Co-Owner · Livery & Radical Program",
      initials: "SM",
      img: "assets/face-sam-mcdougall.webp",
      bio: "Co-owner and the Radical program's driver. Designed every livery Eclipse runs, from the purple LMDh to the FIS fleet.",
      tint: "purple",
    },
  ],
  staff: [
    {
      name: "Tanner DeFabis",
      role: "Admin · Formula Program",
      initials: "TD",
      img: "assets/face-tanner-defabis.webp",
      bio: "Runs the open-wheel program. Won the Freedom 75 in the real world. Took FIS Round 2 at Pocono and raced in the Indy 500 lineup.",
    },
    {
      name: "Griffin Yellin",
      role: "Admin · Setup Engineer",
      initials: "GY",
      img: "assets/face-griffin-yellin.webp",
      bio: "Runs vehicle dynamics. Works alongside Michael on setup development, strategy and operations, and keeps the programs moving day to day. Building Eclipse's AI-assisted setup platform with Michael and Tristan.",
    },
    {
      name: "Jeremy Fairbairn",
      role: "Admin · Endurance Lead",
      initials: "JF",
      img: "assets/face-jeremy-fairbairn.webp",
      bio: "Runs the endurance program. British F4 race winner in the real world. Co-won Petit Le Mans and takes the long stints at Daytona, Sebring, Bathurst and Spa.",
    },
    {
      name: "Tristan Moss",
      role: "Admin · Setup Advisor",
      initials: "TM",
      img: "assets/face-tristan-moss.webp",
      bio: "Won the Indy 500 and the Brickyard 400 for Eclipse. Advises on setup across the endurance and Formula programs.",
    },
    {
      name: "Sybren Stoel",
      role: "Partner · Owner, SJS Games",
      initials: "SS",
      bio: "Owns SJS Games and has partnered with Eclipse on programs and events for years.",
    },
  ],
  drivers: [
    { name: "Max Taylor",          note: "IndyNXT Race Winner",   initials: "MT", img: "assets/face-max-taylor.webp",           programs: ["Formula", "GTP"] },
    { name: "Devlin DeFrancesco",  note: "IndyCar · Endurance",    initials: "DD", img: "assets/face-devlin-defrancesco.webp",   programs: ["Formula", "GTP"] },
    { name: "Peter Dempsey",       note: "Indy Lights Winner",     initials: "PD", img: "assets/face-peter-dempsey.webp",        programs: ["GTP", "LMP2"] },
    { name: "Evagoras Papasavvas", note: "Endurance · GTP",        initials: "EP", img: "assets/face-evagoras-papasavvas.webp",  programs: ["GTP", "LMP2"] },
    { name: "Barrett Wolfe",       note: "Endurance · GT3",        initials: "BW", img: "assets/face-barrett-wolfe.webp",        programs: ["GT3"] },
    { name: "Drew Szuch",          note: "Formula · Endurance",    initials: "DS", img: "assets/face-drew-szuch.webp",           programs: ["Formula", "LMP2"] },
    { name: "Alex Berg",           note: "British F4 Race Winner", initials: "AB", img: "assets/face-alex-berg.webp",            programs: ["GTP", "LMP2"] },
    { name: "Bryson Morris",       note: "IMPC Multi-Race Winner", initials: "BM", img: "assets/face-bryson-morris.webp",        programs: ["Formula"] },
    { name: "Zach Fourie",         note: "F4 US Driver",           initials: "ZF", img: "assets/face-zach-fourie.webp",          programs: ["Formula"] },
    { name: "Tyke Durst",          note: "USF Pro 2000 Driver",    initials: "TD", img: "assets/face-tyke-durst.webp",           programs: ["Formula", "LMP2"] },
  ],
  events: [
    { mo: "JAN", d: "9–10",  t: "Roar Before the 24",     v: "Daytona International Speedway",  c: "LMP2" },
    { mo: "JAN", d: "16–18", t: "Daytona 24",              v: "Daytona International Speedway",  c: "GTP · LMP2 · GT3", featured: true },
    { mo: "FEB", d: "20–22", t: "Bathurst 12",             v: "Mount Panorama Circuit",          c: "GT3", featured: true },
    { mo: "MAR", d: "27–29", t: "Sebring 12",              v: "Sebring International Raceway",   c: "GTP · LMP2 · GT3", featured: true },
    { mo: "MAY", d: "1–3",   t: "Nürburgring 24h",         v: "Nürburgring-Gesamtstrecke 24h",   c: "GT3" },
    { mo: "MAY", d: "5–11",  t: "Indy 500 · Fixed",        v: "Indianapolis Motor Speedway",     c: "IndyCar" },
    { mo: "MAY", d: "12–18", t: "Indy 500 · Open",         v: "Indianapolis Motor Speedway",     c: "IndyCar", featured: true },
    { mo: "JUN", d: "19–21", t: "Watkins Glen 6 Hour",     v: "Watkins Glen International",      c: "GTP · LMP2 · GT3" },
    { mo: "JUL", d: "10–12", t: "Spa 24",                  v: "Circuit de Spa-Francorchamps",    c: "GT3" },
    { mo: "JUL", d: "24–26", t: "6 Hours of Road America", v: "Road America",                    c: "GTP · LMP2 · GT3" },
    { mo: "SEP", d: "10–15", t: "Suzuka 1000km",           v: "Suzuka Circuit",                  c: "GT3" },
    { mo: "SEP", d: "18–20", t: "Britcar 24",              v: "Silverstone",                     c: "GT3" },
    { mo: "SEP", d: "25–27", t: "Petit Le Mans",           v: "Michelin Raceway Road Atlanta",   c: "GTP · LMP2 · GT3", featured: true },
    { mo: "OCT", d: "16–18", t: "8 Hours of Indianapolis", v: "Indianapolis Motor Speedway",     c: "GT3" },
  ],
  gallery: [
    { img: "assets/media-imola-499p-02.webp",    caption: "499P · Imola",                    tag: "RACE" },
    { img: "assets/media-imola-499p-01.webp",    caption: "499P · Imola",                    tag: "RACE" },
    { img: "assets/media-april-2026.webp",       caption: "April 2026 · Endurance",          tag: "RACE" },
    { img: "assets/media-04.webp",               caption: "Sebring 12 · March 2026",         tag: "RACE" },
    { img: "assets/media-03.webp",               caption: "GTP · Night Pace",                tag: "RACE" },
    { img: "assets/media-02.webp",               caption: "Global Endurance · October 2025", tag: "RACE" },
    { img: "assets/media-01.webp",               caption: "September 2025 · Endurance",      tag: "RACE" },
    { img: "assets/media-michael-portrait.webp", caption: "Michael Costello · Founder",      tag: "PIT WALL" },
  ],
  sponsors: [
    { name: "Mosaic Animal Health at St. Hubert's", short: "MOSAIC AHC",     type: "PARTNER", logo: "assets/sp-st-huberts.webp" },
    { name: "Ronald McDonald House Charities",      short: "RMHC",           type: "CHARITY", logo: "assets/sp-rmhc.webp" },
    { name: "Hope 4 AL",                            short: "HOPE4AL",        type: "CHARITY", logo: "assets/sp-hope4al.webp" },
    { name: "ProGuard Automotive",                  short: "PROGUARD",       type: "SPONSOR", logo: "assets/sp-proguard.webp" },
    { name: "Destination Athlete",                  short: "DEST. ATHLETE",  type: "SPONSOR", logo: "assets/sp-destination-athlete.webp" },
    { name: "EDA Frames Eyewear",                   short: "EDA FRAMES",     type: "SPONSOR", logo: "assets/sp-eda-frames.webp" },
    { name: "Rayne Nutrition",                      short: "RAYNE",          type: "SPONSOR", logo: "assets/sp-rayne.webp" },
    { name: "iwis",                                 short: "IWIS",           type: "SPONSOR", logo: "assets/sp-iwis.webp" },
    { name: "Bell Helmets",                         short: "BELL",           type: "SPONSOR", logo: "assets/sp-bell.webp" },
    { name: "100%",                                 short: "100%",           type: "SPONSOR", logo: "assets/sp-ride-100.webp" },
  ],
};
